### ISSUE TITLE
react-hot-loader version 4.8.1 no longer exists

### ISSUE THREAD

**Issue by capmonty** [wonism/gatsby-advanced-blog#16]
`package-lock.json` needs an update because `react-hot-loader@4.8.1` does not exist

**Comment by wonism** [comment]
Thanks for reporting this :)
I will look into it.

**Comment by wonism** [comment]
fixed by https://github.com/wonism/gatsby-advanced-blog/commit/3a4a61f0f62f3c1e3e6035800f4535297aa34359
