### ISSUE TITLE
Robots exclusion standard missing

### ISSUE THREAD

**Issue by puresight** [wonism/gatsby-advanced-blog#19]
Error 404 returned for robots.txt file

**Comment by wonism** [comment]
I added some plugins to generate robots.txt :)
It works on 1.1.4
https://github.com/wonism/gatsby-advanced-blog/commit/e48b4ecf61b5992ebd2c0b7a25ef330936927233#diff-b9e136416b90437fa1dac910280b45fc

**Comment by puresight** [comment]
Nice!
