### ISSUE TITLE
Gatsby links needs to be update to new format

### ISSUE THREAD

**Issue by rjpruitt16** [wonism/gatsby-advanced-blog#8]
For example, 

import Link from 'gatsby-link';

to,

import { Link } from 'gatsby'

as documentation
https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#import-link-from-gatsby

**Comment by rjpruitt16** [comment]
Also, I would not mind fixing it myself.

**Comment by wonism** [comment]
Thank you for pointing out :)
It is resolved with b82f187bf28b048d8b5b6f5c50520c21f121a12f
