### ISSUE TITLE
Style Components do not work even after adding them to peer review and installing.

### ISSUE THREAD

**Issue by rjpruitt16** [wonism/gatsby-advanced-blog#9]
I used to get warn error Style Components was not in peer. So, I change the location to peer review as below.

  "peerDependencies": {
    "gatsby": "^2.0.0-beta.19",
    "react": "^16.4.0",
    "prop-types": "^15.0.0",
    "styled-components": "^3.3.3"
  },

Then, I install styled-components. The warning went away, but the component's css is absent in deployment and gatsby serve.

**Comment by wonism** [comment]
Thank you for pointing out :)
It is resolved with b82f187bf28b048d8b5b6f5c50520c21f121a12f
